import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar/Navbar";
import { Toaster } from "sonner";
import { GlobalProvider } from "./contexts/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "My Finances",
	description: "Generated by create next app",
};

import { createTheme, ThemeProvider } from "@mui/material/styles";
import { theme } from "./Theme";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex">
					<GlobalProvider>
						<ThemeProvider theme={theme}>
							<Toaster richColors />
							<Navbar />
							{children}
						</ThemeProvider>
					</GlobalProvider>
				</div>
			</body>
		</html>
	);
}
